name: Deploy Vue + Vite to GitHub Pages

on:
  push:
    branches:
      - deploy # branch que você usa como principal (pode ser "master" ou outro)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Configuração do Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16 # Versão do Node.js

      # Instalar dependências
      - name: Install dependencies
        run: npm install

      # Construir o projeto
      - name: Build project
        run: npm run build

      # Deploy para o GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
